input {
  beats { port => 5044 }
  tcp   { port => 50000 codec => json_lines }
}
filter { }  # (add grok here if you want)
output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user  => "${ELASTIC_USERNAME}"
    password => "${ELASTIC_PASSWORD}"
    index => "training-%{+YYYY.MM.dd}"
  }
}
